### PR TITLE
dont start app if PORT not provided

### PR DESCRIPTION
**Pull request by aceakash**
@quii is this a good use of `panic`?

### CODE REVIEW

**Comment by aceakash** [comment]
...disregarding the fact that ideally `getPort()` should return `""` and `main()` should be the one to panic :-)

**Comment by quii** [comment]
I think `log.Fatal` might be nicer, less mess

**Comment by quii** [comment]
As in i think a panic will give a trace and stuff, dont really need it

**Comment by aceakash** [comment]
Raised https://github.com/mergermarket/goMakeIt/pull/8 which should supersede this... closing ...

Will change `panic` to a log and `return`

**Pull request closed without merging**
